### ISSUE TITLE
Dont work at docs.google.com/spreadsheets

### ISSUE THREAD

**Issue by EnayUA** [farblos/copy-on-select-2#1]
Hi.

Your Extension buged, it did not work propertly at docs.google.com/spreadsheets - when select one or multiple cell you can't paste any text even copyed by CTRL/CMD+C to another cell on Win and Mac. Also in MacOS dont work menu by duble tap(RMC Win).

**Comment by farblos** [comment]
My first issue ever - cool.

As mentioned [here](https://github.com/farblos/copy-on-select-2), this extension is extremely simple.  I checked on Google docs, and there is simply no reasonable selection available on these pages that the extension could access.

But from what I understand from your bug report, the extension even breaks regular copy and paste on docs.google.com - is that correct?

Um, yes, seems that I can reproduce that on Firefox on Linux: Select one cell, Ctrl-C, select another cell, Ctrl-V, nothing happens.  With extension disabled, things work fine.  Will see what I can do about that.

**Comment by farblos** [comment]
For spreadsheets docs.google.com provides a non-empty but completely meaningless selection in `document.getSelection()`.  That lets the extension call `document.execCommand('copy')`, which (presumably) interferes with the *real* selection made by docs.google.com.

There do not seem to be any special properties in the selection provided by docs.google.com which distinguishes them from regular text selections, so the only way to make this work seems to be something like: "if selection made on docs.google.com, then do not process it."  Bah.

Will try to implement sth along these lines.

**Comment by farblos** [comment]
Processed the GitHub paperworks, will upload to AMO over the weekend.

**Comment by farblos** [comment]
Done.
Just in case somebody is interested in the details: The fix for this issue is rather crude - this extension simply ignores all events on pages from `docs.google.com` in a hard-coded way. 
Should the ever-growing user-base come accross a larger number of such sites, I probably need to extend that approach to something more scalable and configurable...
