### ISSUE TITLE
Version for chromium web browsers

### ISSUE THREAD

**Issue by trimechee** [farblos/copy-on-select-2#10]
Hello, thank you so much for this great awesome amazing extension ! 🥇 💯 

We have resquest please :  we use sometime ungoogled chromium browser and it will be great if there is version for chromium web browser even outside chrome web store because in ungooled chromium browser, we can add extensions outside the chrome store, thank you very much :)

**Comment by farblos** [comment]
I won't promise anything ... this seems to be comprise a V3 manifest (which I intended to do, anyway), plus polyfilling.  If it's not much more than that, I could consider doing it.  Eventually.

Just curious: Aren't there any similar extensions available in the Chrome Web Store?  What about [this one](https://chrome.google.com/webstore/detail/auto-copy/bijpdibkloghppkbmhcklkogpjaenfkg)?  Or is the Chrome Web Store not accessible in ungoogled chromium?

**Comment by trimechee** [comment]
press article reports that many extensions on the chrome web store have malware, viruses, scams, ads....I know this extension but I refuse to try it, I am not saying this extension contains malware but I I'm wary of extensions that are not open source and don't have an official site....that says Google will force developers on the play store to give their real identity in order to better detect malicious applications... in any case thank you for your help and when firefox and chrome have the same manifest API v3, maybe our beloved copy-on-select-2 will be compatible with the chrome web store, thanks again :)

**Comment by trimechee** [comment]
May be to use  Copy-on-select-2 on ungoogled chromium, i will use these extensions : 


https://foxified.org/
https://crosspilot.io/
Chameleon
https://chrome.google.com/webstore/detail/chameleon/dmpojjilddefgnhiicjcmhbkjgbbclob
https://sereneblue.github.io/chameleon/



or i will use this extension which seems reliable because even if it is not open source, it has an official website:

https://stratusnine.com/software/auto-copy/

**Comment by trimechee** [comment]
Oups I just checked, I realize that it's the same chrome extension that you recommended to me lol....I'm going to try this chrome extension but do you think it's a reliable extension without security risk please?

**Comment by farblos** [comment]
> I'm going to try this chrome extension but do you think it's a reliable extension without security risk please?

Don't have a reply to that, sorry:

-  Unfortunately, the author has an official website, but nothing where you could easily check the sources.
- And besides that, the extension promises to have "many options", which in any case should make it more difficult to evaluate w.r.t. security.
- Finally, I don't think I'm in the right position to assess other developer's software.

I guess you have to rely on Google's checks and on other user's ratings here ...

BTW, thanks for the links to foxified et al.  Looks interesting.

**Comment by trimechee** [comment]
Great, thank you :)

**Comment by farblos** [comment]
@trimechee I did a draft release 2.6.0 that also comes with a CRX package, I hope this is still relevant for you :-).

For the record and also for my reference:
- Manifest V3 extensions for Firefox have the security constraint that all users have to explicitly grant "access to web data" permissions for extensions with content scripts (like this extension).  See [here](https://extensionworkshop.com/documentation/develop/manifest-v3-migration-guide/#host-permissions).
- There is still hope that FF development eases that situation for extension without any UI input elements (like this extension).  See [here](https://discourse.mozilla.org/t/extensions-using-content-scripts-without-any-user-action-wont-work-anymore-in-mv3/98728).
- So I decided for the time being to keep manifest V2 for the XPI, but create the CRX with manifest V3.

Anyway, I have never really been sure whether only I can see draft releases or others as well. So could you please navigate to the [releases](https://github.com/farblos/copy-on-select-2/releases) and check whether you can see a version 2.6.0 there.
If that fails, could you next check whether you can access [this link](https://github.com/farblos/copy-on-select-2/releases/download/untagged-67572091895e1d266295/copy-on-select-2-2.6.0.crx) that should directly download the CRX.
If that fails as well, I'll provide the CRX as an attachment to this issue, I guess.

I still need to test this a bit and to brush it up, but test results from your end would be helpful as well.

**Comment by trimechee** [comment]
Ohh thank you o much Mr @farblos for all efforts to make new versions of this wonderful great extension ! 💯 🥇 

Yes of course, with pleasure, it's the minimum we can do :) for the first link, I tried with firefox and edge browser, i only see " copy-on-select-2-unsigned-2.5.xpi ", 
for the second link, i have "page not found 404" in edge browser, and same error message when i use firefox browser "this is not the web page you are looking for" !

**Comment by farblos** [comment]
Thanks for testing, @trimechee!

Here is the [CRX package](https://github.com/farblos/copy-on-select-2/files/13773366/copy-on-select-2-2.6.0.zip), I hope you can download that.  Please rename from `.zip` to `.crx`  and test when you have time to.  There is a minor known issue on chrome-based browsers, please see [the readme](https://github.com/farblos/copy-on-select-2/tree/10-version-for-chromium-web-browsers#known-issues).

I plan to fix that with issue #12.

**Comment by trimechee** [comment]
Yes, of course , with pleasure in sha Allah ! Thank you so much @farblos :)

I would like to point out that a few days ago, I discovered this worrying article concerning ungoogled chromium : 

https://qua3k.github.io/ungoogled/

It scared me so I decided to uninstall all chromium and ungoogled chromium browsers from my computer, the ungoogled chromium team says this article is old and several problems have been fixed : 

https://github.com/ungoogled-software/ungoogled-chromium/discussions/2568

  but I decided to replace chromium and ungoogled chromium browsers with edge browser which has an energy saving option even on desktop and allows you to block wasm webassembly.....


I will try to install the extension via edge and chrome and opera in sha Allah and I will share my impressions....

**Comment by farblos** [comment]
> but I decided to replace chromium and ungoogled chromium browsers with edge browser

Sure, everybody has its own preferences and sometimes these change ... anyway, the CRX passes my tests and so I released it.  I won't release the XPI on AMO, though, since there are no FF-specific changes.

I'll close this issue.  If you have any findings to add, pls add them on the closed issue, I should notice them there as well.

**Comment by trimechee** [comment]
Great ! I am testing the new extension and and I will share with you my impressions if I find any problems or bugs, thank you very much :)

**Comment by trimechee** [comment]
Hello @farblos , i tried with edge browser, i rename zip to crx and enable developer mode but edge doesn't allow me to enable thise extension.....the new version is not present in chrome web store or edge store ?

**Comment by farblos** [comment]
Hi @trimechee, nope, no chrome web store or edge store, sorry.  These are a too commercial and non-free for my taste, so I'll release the CRX only for those chromium-based browsers that can install extensions directly from file.

**Comment by trimechee** [comment]
We understand, thank you :) people say microsoft edge browser is free, i.e. developers can put their extensions in the Microsoft Edge Store for free without paying anything to Microsoft unlike Chrome Web Store which apparently requires payment, have you tried putting your magnificent extension on the Microsoft Edge Store? or in opera browser store? There is also a popular Korean browser, Naver Whale Browser which also has a store for extensions:

https://store.whale.naver.com/extensions/popular

**Comment by farblos** [comment]
Thanks for trying to convince me otherwise, but:

- This is not actually about price, but more about principle.  [Chrome](https://en.wikipedia.org/wiki/Google_chrome) and [Edge](https://en.wikipedia.org/wiki/Microsoft_Edge) are both proprietary browsers (see the "License" field in Wikipedia), and I don't want to support these.  Even if that means that I loose some nice users :-).

- Also, maintaing other extension stores means more work, while the CRX gets built (from now on) automatically, without extra work.

(As a side note, I already half regret supporting chromium-based browsers. I currently work on issue #12, and FF and chromium behave differently in funny and unexpected ways when it comes to selection in input fields ...)

**Comment by trimechee** [comment]
Ohh we undestand and thank you for all your hard work to invent great extensions :) i am waiing for the new version of Thorium browser that use chromium son i think we will be able to test crx extension without the need of commercial addons stores.....thank you again :) there is extension like "foxified" so we can even emulate and use firefox extensions in chrome and edge browsers !
